// Institutions

// Create institution
POST https://localhost:20011/institutions
Content-Type: application/json

{
    "name": "Institution1",
    "description": "Demo institution 1"
}

###

// Get institution
GET https://localhost:20011/institutions/019a8771-fcfe-7663-b1c6-75703a3f771b

###

// Get institutions
GET https://localhost:20011/institutions


###

// Get institution with customers
GET https://localhost:20011/institutions/019a8771-fcfe-7663-b1c6-75703a3f771b?includeCustomers=true

###

// Get institutions with customers
GET https://localhost:20011/institutions?includeCustomers=true

###

// update institution
PUT https://localhost:20011/institutions/019a86a3-4c73-73cb-bc5e-eba5d34f920d
Content-Type: application/json

{
    "name": "Institution1 updated",
    "description": "Demo institution 1 updated"
}

###

// patch institution
PATCH https://localhost:20011/institutions/019a86a3-4c73-73cb-bc5e-eba5d34f920d
Content-Type: application/json

{
    "name": "Institution1 patched"
}
###

// delete institution
DELETE https://localhost:20011/institutions/019a83f6-1881-703a-8c8a-a669848ddbe1

###
