// Institution

// Create institution
POST https://localhost:20011/institutions
Content-Type: application/json

{
    "name": "Institution1",
    "description": "Demo institution 1"
}

###

// Get institution
GET https://localhost:20011/institutions/id

###

// Get institutions
GET https://localhost:20011/institutions


###

// update institution
PUT https://localhost:20011/id
Content-Type: application/json

{
    "name": "Institution1 updated",
    "description": "Demo institution 1 updated"
}

###

// patch institution
PATCH https://localhost:20011/id
Content-Type: application/json

{
    "name": "Institution1 patched"
}
###

// delete institution
DELETE https://localhost:20011/id

###
