// Institutions

@tokenUser = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJjdXN0b21lcnMuYXBpIiwiaXNzIjoiaHR0cHM6Ly9hdXRoLmN1c3RvbWVycy5hcGkiLCJleHAiOjE3NjQ1MTIzNjAsInN1YiI6IjI3YWZkNzg0LThiYzYtNDlhMC04Njk1LWM0YTRjZDcwOGY0NiIsImVtYWlsIjoidXNlcjFAZW1haWwuY29tIiwiY29tcGFueSI6IkNvbXBhbnkgMSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6Ik1lbWJlciIsInBlcm1pc3Npb24iOiJkYXRhOnJlYWQiLCJpYXQiOjE3NjQ1MTE3NjAsIm5iZiI6MTc2NDUxMTc2MH0.ORwTWuLOEOrYDtW3DWeOa-hMvhFRC3p2NpcTA5U38y8

@tokenAdmin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJjdXN0b21lcnMuYXBpIiwiaXNzIjoiaHR0cHM6Ly9hdXRoLmN1c3RvbWVycy5hcGkiLCJleHAiOjE3NjQ1MTE5MTEsInN1YiI6IjZjNDgyNzIxLTAyMjctNGIzMC1iNjE1LWU4Y2E0OTc4Zjg1NyIsImVtYWlsIjoiYWRtaW5AZW1haWwuY29tIiwiY29tcGFueSI6IkFkbWluIENvcnAiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsInBlcm1pc3Npb24iOlsiZGF0YTpyZWFkIiwiZGF0YTpyZW1vdmUiLCJkYXRhOndyaXRlIl0sImlhdCI6MTc2NDUxMTMxMSwibmJmIjoxNzY0NTExMzExfQ.yS7V1bPuNyNpiYI7mButRgFGXTQDovDUBao731vpCwQ


// Create institution
POST https://localhost:20011/institutions
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

{
    "name": "Institution1",
    "description": "Demo institution 1"
}

###

// Get institution
GET https://localhost:20011/institutions/019ad512-4abc-747f-bc48-3eb1a9206dd3
Authorization: Bearer {{tokenUser}}

###

// Get institutions
GET https://localhost:20011/institutions
Authorization: Bearer {{tokenAdmin}}

###

// Get institution with customers
GET https://localhost:20011/institutions/019a8771-fcfe-7663-b1c6-75703a3f771b?includeCustomers=true

###

// Get institutions with customers
GET https://localhost:20011/institutions?includeCustomers=true

###

// update institution
PUT https://localhost:20011/institutions/019a86a3-4c73-73cb-bc5e-eba5d34f920d
Content-Type: application/json

{
    "name": "Institution1 updated",
    "description": "Demo institution 1 updated"
}

###

// patch institution
PATCH https://localhost:20011/institutions/019a86a3-4c73-73cb-bc5e-eba5d34f920d
Content-Type: application/json

{
    "name": "Institution1 patched"
}
###

// delete institution
DELETE https://localhost:20011/institutions/019a83f6-1881-703a-8c8a-a669848ddbe1

###
